# Generated by Django 3.2.7 on 2021-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210923_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(),
        ),
    ]
